In [19]:
from src.data.dataloader import *
from src.data.csv_generator import save_to_csv


import pandas as pd


df_image = get_image_data()
#df_caption = get_caption_dataset(df_image)

save_to_csv(df_image, 'data/newyorker_caption_contest/df_complete.csv')

ImportError: cannot import name 'save_to_csv' from 'src.data.csv_generator' (c:\Users\idont\Documents\ADA\ada-2025-project-data_dinosaur\src\data\csv_generator.py)

In [11]:
df_image.to_csv("data/newyorker_caption_contest/df_complete.csv", index=False)

In [ ]:
df_caption

,contest_id,date,rank,caption,mean,precision,votes,not_funny,somewhat_funny,funny
0,510,2016-03-07,0,I'm a congressman--obstruction is my job.,1.913043,0.094022,69,24,27,18
1,510,2016-03-07,1,"I'm what they mean when they say, 'The middle ...",1.842105,0.191381,19,8,6,5
2,510,2016-03-07,2,Does this suit make me look flat?,1.711111,0.112915,45,21,16,8
3,510,2016-03-07,3,"When the right woman comes along, I'll know it.",1.625000,0.116657,32,15,14,3
4,510,2016-03-07,4,"I used to lie in the gutter, but then I quit d...",1.617647,0.133610,34,19,9,6
...,...,...,...,...,...,...,...,...,...,...
2263043,895,2023-09-18,4953,Looks like we took a wrong turn at the Hubble ...,1.023256,0.016347,86,84,2,0
2263044,895,2023-09-18,4954,Post-modern just doesn't do it for me.,1.022222,0.015625,90,88,2,0
2263045,895,2023-09-18,4955,How was I supposed to know they covered themse...,1.020833,0.014654,96,94,2,0
2263046,895,2023-09-18,4956,"No, they wanted us to teleport the giveaway ca...",1.020619,0.020619,97,96,0,1
2263047,895,2023-09-18,4957,"The cinema is still here, but they aren’t play...",1.012195,0.012270,82,81,1,0

In [ ]:
df_image

,contest_id,num_captions,image_locations,image_descriptions,image_uncanny_descriptions,entities,questions,Top Rated caption,The New Yorker's winner,date,Number of votes
0,510,3905.0,[the street],[A man is relaxing on a city street. Others ar...,[A man is just laying in the middle of the sid...,[https://en.wikipedia.org/wiki/Bystander_effec...,[Why is he laying there?],“I'm a congressman--obstruction is my job.”,NaN,2016-03-07,82627
1,511,3325.0,"[the front hard, a residential walkway]",[A man in a winter coat and cap is looking at ...,[It's unusual to see someone holding a snow sh...,"[https://en.wikipedia.org/wiki/Snowball_fight,...",[Is the man overly small or the shovel overly ...,“I'm hourly.”,NaN,2016-03-14,56660
2,512,4399.0,"[yoga place, a yoga studio]",[A man and woman are standing facing one anoth...,[Nothing is really out of place in this image....,"[https://en.wikipedia.org/wiki/Rug, https://en...","[Why is the man carrying a huge rug?, Why is t...","“We're pretentious, not ostentatious.”",NaN,2016-03-21,43120
3,513,4141.0,"[a workplace, an elevator]",[Three business men are walking down a hall. T...,[A suit case is usually carried by one person ...,[https://en.wikipedia.org/wiki/Worker_cooperat...,[Why is the briefcase big enough for three peo...,"“I'm just saying, I can see why the 'brief'cas...",NaN,2016-03-27,34013
4,514,3951.0,[plains],[Some cowboys are riding through the desert. T...,[There are rocking horses in place of real hor...,"[https://en.wikipedia.org/wiki/Rocking_horse, ...",[Why is this chase taking place?],"“No, you grow up”",NaN,2016-04-03,192198
...,...,...,...,...,...,...,...,...,...,...,...
379,891,NaN,NaN,NaN,NaN,NaN,NaN,"“Sorry, only the catcher works from home.”",NaN,2023-08-21,928856
380,892,NaN,NaN,NaN,NaN,NaN,NaN,"“Yes, it's called Thesaurus, but you're not re...",NaN,2023-08-28,788251
381,893,NaN,NaN,NaN,NaN,NaN,NaN,“The seller isn't willing to come down.”,NaN,2023-09-04,1085745
382,894,NaN,NaN,NaN,NaN,NaN,NaN,“See how the nose seems to follow you?”,NaN,2023-09-11,878676
383,895,NaN,NaN,NaN,NaN,NaN,NaN,“Do you think death rays would be considered e...,NaN,2023-09-18,777820